### ISSUE TITLE
ValueError: current limit exceeds maximum limit  error if run auto_mhddos_mac script against macOS 10.15(10.13)

### ISSUE THREAD

**Issue by johnbunky** [porthole-ascend-cinnamon/mhddos_proxy#125]
Environment: MacOS 10.15 , Python 3.10.4

yous-Air:~ you$ curl -LO https://raw.githubusercontent.com/alexnest-ua/auto_mhddos_mac/main/runner.sh && bash runner.sh 200 1000 --debug --vpn

python3 runner.py -c https://raw.githubusercontent.com/alexnest-ua/targets/main/special/archive/9may/9may_l7_2 --rpc 1000 -t 1000 --vpn --debug
[13:33:53 - INFO] 'uvloop' успішно активований (підвищенна ефективність роботи з мережею)

- Навантаження (кількість потоків) - параметр `-t 5000`, за замовчуванням - 7500
- Статистика у вигляді таблиці або тексту - прапорець `--table` або `--debug`
- Повна документація - https://github.com/porthole-ascend-cinnamon/mhddos_proxy
    
Exception in thread Thread-1 (_main):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/you/mhddos_proxy/runner.py", line 397, in _main
    loop.run_until_complete(start(args))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/you/mhddos_proxy/runner.py", line 336, in start
    max_conns = fix_ulimits()
  File "/Users/you/mhddos_proxy/src/system.py", line 34, in fix_ulimits
    resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))
ValueError: current limit exceeds maximum limit

NOTES: There is the same issue on macos 10.13

**Comment by porthole-ascend-cinnamon** [comment]
Please add the output for these command:
```
ulimit -Sn
ulimit -Hn
```

**Comment by porthole-ascend-cinnamon** [comment]
Please also run this python script and provide the last several lines of the output

```
import asyncio,resource, sys,os
opened = 0
async def task():
    global opened
    reader, writer = await asyncio.open_connection('1.1.1.1', '53')
    opened += 1
    await asyncio.sleep(5)
    writer.close()
    await writer.wait_closed()

asyncio.run(asyncio.wait([
    task() for _ in range(5000)
]))
print(opened, resource.getrlimit(resource.RLIMIT_NOFILE))
print(sys.platform, os.name)
```

**Comment by porthole-ascend-cinnamon** [comment]
Also, this commands)

```
sysctl kern.maxfiles
sysctl kern.maxfilesperproc
```

**Comment by johnbunky** [comment]
> ulimit -Sn 32768

yous-Air:~ you$ ulimit -Sn
256
yous-Air:~ you$ ulimit -Hn
unlimited
yous-Air:~ you$ ulimit -Sn 32768
-bash: ulimit: open files: cannot modify limit: Invalid argument

**Comment by johnbunky** [comment]
> 

Traceback (most recent call last):
  File "/Users/you/test.py", line 5, in task
    reader, writer = await asyncio.open_connection('1.1.1.1', '53')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 943, in _connect_sock
    sock = socket.socket(family=family, type=type_, proto=proto)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
250 (256, 9223372036854775807)
darwin posix

**Comment by johnbunky** [comment]
> sysctl kern.maxfilesperproc

yous-Air:~ you$ sysctl kern.maxfiles
kern.maxfiles: 12288
yous-Air:~ you$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240

**Comment by porthole-ascend-cinnamon** [comment]
Try running these commands, and restart runner afterwards in same terminal

```
sysctl -w kern.maxfiles=65536
sysctl -w kern.maxfilesperproc=65536
```

**Comment by johnbunky** [comment]
> sysctl -w kern.maxfilesperproc=65536

yous-Air:~ you$ sysctl -w kern.maxfiles=65536
kern.maxfiles: 12288
sysctl: kern.maxfiles=65536: Operation not permitted
yous-Air:~ you$ sysctl -w kern.maxfilesperproc=65536
kern.maxfilesperproc: 10240
sysctl: kern.maxfilesperproc=65536: Operation not permitted

**Comment by porthole-ascend-cinnamon** [comment]
Well, seems you are out-of-luck. Unless you (or anyone) finds the way to raise your soft limit, you are stuck with 250 threads max. You can run the latest version and it won't fail, but 250 threads won't do much, unfortunately. Google is your best friend now.

**Comment by johnbunky** [comment]
Ah! I got it!!!))
yous-Air:~ you$ sudo sysctl -w kern.maxfiles=65536
Password:
kern.maxfiles: 12288 -> 65536
yous-Air:~ you$ sudo sysctl -w kern.maxfilesperproc=65536
kern.maxfilesperproc: 10240 -> 65536

**Comment by porthole-ascend-cinnamon** [comment]
Does it work now?

**Comment by johnbunky** [comment]
sudo sysctl -w kern.maxfiles=200000
sudo sysctl -w kern.maxfilesperproc=200000
Unfortunately nothing changed(
[18:03:55 - WARNING] Кількість потоків зменшено до 206 через обмеження вашої системи
..............
[20-05-2022 18:04:20] - Starting our new proxy_finder, next restart in 1200...
Traceback (most recent call last):
  File "/Users/you/proxy_finder/finder.py", line 205, in <module>
    main_wrapper()
  File "/Users/you/proxy_finder/finder.py", line 180, in main_wrapper
    fix_ulimits()
  File "/Users/you/proxy_finder/core.py", line 53, in fix_ulimits
    resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))
ValueError: current limit exceeds maximum limit

**Comment by porthole-ascend-cinnamon** [comment]
It's strange that your are still getting errors from proxy_finder, it should run with warning on 206 threads same as mhddos_proxy. Try to delete the /Users/you/proxy_finder/ folder. This is still bad since you cannot run > 200 threads. Google for "raise open files limit {MY OS}" and try some of the proposed solutions.

**Comment by johnbunky** [comment]
quick report: 
yous-Air:proxy_finder you$ launchctl limit maxfiles
	maxfiles    256            unlimited      
yous-Air:proxy_finder you$ sudo launchctl limit maxfiles 64000 524288
Password:
yous-Air:proxy_finder you$ launchctl limit maxfiles
	maxfiles    64000          524288         
yous-Air:proxy_finder you$ python3 finder.py 
Traceback (most recent call last):
  File "/Users/you/proxy_finder/finder.py", line 205, in <module>
    main_wrapper()
  File "/Users/you/proxy_finder/finder.py", line 180, in main_wrapper
    fix_ulimits()
  File "/Users/you/proxy_finder/core.py", line 53, in fix_ulimits
    resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))
ValueError: current limit exceeds maximum limit

But there are a good news too(: mhddos works without the ValiueError

**Comment by porthole-ascend-cinnamon** [comment]
Closing due to inactivity.
Try one of these solutions

https://superuser.com/a/1171026
https://neo4j.com/developer/kb/setting-max-open-file-limits-on-osx/
https://gist.github.com/skylock/0117ec637d468f91260927b43b816eda
https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c
