### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 25-29: ordinal not in range(256)

### ISSUE THREAD

**Issue by CPAprince** [porthole-ascend-cinnamon/mhddos_proxy#138]
UBUNTU 20 
Pip and all requirments installed

root@soda:~/mhddos_proxy# python3 runner.py --itarmy --debug

Traceback (most recent call last):
  File "runner.py", line 422, in <module>
    main()
  File "runner.py", line 391, in main
    print_banner(args)
  File "/root/mhddos_proxy/src/output.py", line 87, in print_banner
    print(*rows, sep='\n')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 25-29: ordinal not in range(256)
root@soda:~/mhddos_proxy#

**Comment by CPAprince** [comment]
root@soda:~/mhddos_proxy# python3 runner.py
[03:55:36 - ERROR] \u041d\u0435 \u0432\u043a\u0430\u0437\u0430\u043d\u043e \u0436\u043e\u0434\u043d\u043e\u0457 \u0446\u0456\u043b\u0456 \u0434\u043b\u044f \u0430\u0442\u0430\u043a\u0438


NEWER HAD SUCH Errors before?

**Comment by porthole-ascend-cinnamon** [comment]
On the last message it says "Не вказано жодної цілі для атаки". Try pulling latest version and running with `--lang en` - there was one bit of UA message even in the EN output.

**Comment by porthole-ascend-cinnamon** [comment]
Solved? Re-open if needed
