### ISSUE TITLE
Getting error when running container

### ISSUE THREAD

**Issue by localdotcom** [porthole-ascend-cinnamon/mhddos_proxy#19]
Hi, I'm running tool on kubernetes and getting following errors in log:
```
Traceback (most recent call last):
  File "/mhddos_proxy/dependencies/yarl/_url.py", line 170, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'site_name"'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 255, in <module>
    start(
  File "/mhddos_proxy/./runner.py", line 179, in start
    update_proxies(period, resolved, total_threads)
  File "/mhddos_proxy/./runner.py", line 94, in update_proxies
    CheckedProxies = [
  File "/mhddos_proxy/./runner.py", line 96, in <listcomp>
    for future in as_completed(future_to_proxy) if future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mhddos_proxy/dependencies/PyRoxy/__init__.py", line 124, in check
    if not isinstance(url, URL): url = URL(url)
  File "/mhddos_proxy/dependencies/yarl/_url.py", line 172, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer
```

**Comment by porthole-ascend-cinnamon** [comment]
I need a command to debug it. If you are using `-c https://pastebin` - it;s their ddos protection is messing up with the script.

**Comment by localdotcom** [comment]
Thanks. I'm using -c https://pastebin but it worked till today.

**Comment by localdotcom** [comment]
Solved. I missed `raw` in `-c https://pastebin`
