### ISSUE TITLE
Mac - Intel - OSError: [Errno 101] Network unreachable

### ISSUE THREAD

**Issue by testniger** [porthole-ascend-cinnamon/mhddos_proxy#37]
Mac Intel - DOCKER 
перестало работать - отваливается с такой ошибкой

Traceback (most recent call last):
  File "/mhddos_proxy/dependencies/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/mhddos_proxy/dependencies/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/mhddos_proxy/dependencies/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mhddos_proxy/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/mhddos_proxy/dependencies/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/mhddos_proxy/dependencies/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/mhddos_proxy/dependencies/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/mhddos_proxy/dependencies/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcbca0252a0>: Failed to establish a new connection: [Errno 101] Network unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mhddos_proxy/dependencies/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/mhddos_proxy/dependencies/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/mhddos_proxy/dependencies/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcbca0252a0>: Failed to establish a new connection: [Errno 101] Network unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 241, in <module>
    start(
  File "/mhddos_proxy/./runner.py", line 162, in start
    update_proxies(period, resolved)
  File "/mhddos_proxy/./runner.py", line 76, in update_proxies
    Proxies = list(download_proxies())
  File "/mhddos_proxy/./runner.py", line 64, in download_proxies
    response = requests.get(PROXIES_URL, timeout=10)
  File "/mhddos_proxy/dependencies/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/mhddos_proxy/dependencies/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mhddos_proxy/dependencies/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/mhddos_proxy/dependencies/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/mhddos_proxy/dependencies/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcbca0252a0>: Failed to establish a new connection: [Errno 101] Network unreachable'))

**Comment by porthole-ascend-cinnamon** [comment]
Try restarting the Docker.
