### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by Citizen4our** [porthole-ascend-cinnamon/mhddos_proxy#42]
Hi
During execute throws error:
```
Waiting for proxies initialization. This might take several minutes...
Traceback (most recent call last):
  File "runner.py", line 27, in <module>
    @lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by russian-boat-fuck-you** [comment]
the same issue, yeah!

```
Waiting for proxies initialization. This might take several minutes...
Traceback (most recent call last):
  File "runner.py", line 27, in <module>
    @lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by Citizen4our** [comment]
can you please test locally before pushing to maser? some people already rely on this lib

**Comment by russian-boat-fuck-you** [comment]
Oh, I can see a fix!  Thank you guys for quick reaction!

**Comment by porthole-ascend-cinnamon** [comment]
fixed
@Citizen4our I did test, ofc, with python 3.8. The error happens on the older versions.
