### ISSUE TITLE
Error when starting on digitalocean droplet

### ISSUE THREAD

**Issue by rawenloft** [porthole-ascend-cinnamon/mhddos_proxy#58]
Hi, I got issue when starting on Digitalocena droplet. Before update to last version was all ok
Here is some error message:

> Exception in thread Thread-103:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-185:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-149:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-72:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-132:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1098, in main
    Layer4((ip, port), ref, method, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-91:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-79:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Thread-45:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mhddos_proxy/mhddos/start.py", line 1074, in main
    HttpFlood(thread_id, url, ip, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Such error I get with any target. Please let me know if its my droplet setup or anything else.

**Comment by porthole-ascend-cinnamon** [comment]
Use lower `-t` setting or update your system limits for the max amount of threads. Check if another instance is running. No major changes recently, so it's unlikely related with the update.

**Comment by alexnest-ua** [comment]
Use this: 
`ulimit -n 1048576`

or/and make -t and --rpc not more than 2000 and 500 accordingly

**Comment by porthole-ascend-cinnamon** [comment]
RPC has nothing to do with threads OR connections

**Comment by alexnest-ua** [comment]
But what about this: https://github.com/porthole-ascend-cinnamon/mhddos_proxy/issues/48 ?

**Comment by porthole-ascend-cinnamon** [comment]
@alexnest-ua IDK, you wrote it, same as here. I tell you, that RPC does not affects threads or connections, and your observations lead to false conclusions.

**Comment by rawenloft** [comment]
Gentlemen, no changes, still have same issue when starting on digitalocean droplet. FYI, on virtualbox tested on Kali, works OK.

**Comment by porthole-ascend-cinnamon** [comment]
Have you tried the suggested solutions?

**Comment by porthole-ascend-cinnamon** [comment]
Added some handling of such errors.
