### ISSUE TITLE
Non-rooted device, with Python 3.10 src/dns_utils.py fails

### ISSUE THREAD

**Issue by ultraon** [porthole-ascend-cinnamon/mhddos_proxy#67]
Hello, after installing the `Termux` apk for Android (https://github.com/termux/termux-app/releases/tag/v0.118.0) and configuring everything with the manual https://telegra.ph/mhddos-proxy-for-Android-with-Termux-03-31, I get an error when running the script:
```
~/.../shared/mhddos_proxy $ python runner.py https://<target site> --debug
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 806, in read_resolv_conf
f = stack.enter_context(open(f))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/storage/emulated/0/mhddos_proxy/runner.py", line 13, in <module>
    from src.dns_utils import resolve_host, get_resolvable_targets
File "/storage/emulated/0/mhddos_proxy/src/dns_utils.py", line 10, in <module>
    resolver = dns.resolver.Resolver(configure = True)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 758, in __init__
    self.read_resolv_conf(filename)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 809, in read_resolv_conf
raise NoResolverConfiguration(f'cannot open {f}')
dns.resolver.NoResolverConfiguration: cannot open /etc/resolv.conf
```
It happens because during initialization of the `dns.reolver.Resolver()` instance it tries to read `/etc/resolv.conf` file which is impossible to do on non-rooted devices, and looks like it is not necessary to proceed with the script execution.
To fix that we just need to replace `dns.reolver.Resolver()` with `dns.resolver.Resolver(configure = False)` in this place: https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/2c7dfeb8feae4dc9f815ded0a35d6ae91fc0ea86/src/dns_utils.py#L11

What do you think guys?

**Comment by porthole-ascend-cinnamon** [comment]
You are right, thanks for the great analysis! Already pushed a fixed version.
